unzip(zipfile = 'exdata-data-household_power_consumption.zip')
house.power = read.table(file='./household_power_consumption.txt', header=T, sep=';', na.strings='?')
house.power$Date_Time = as.POSIXct(paste(house.power[,1], house.power[,2]), format="%d/%m/%Y %H:%M:%S")
house.power = house.power[,c(10,2:9)]
house.power = subset(house.power, house.power$Date_Time > as.POSIXct('2007-02-01 00:00:00') & house.power$Date_Time <   as.POSIXct('2007-02-03 00:00:00'))
par(mfrow=c(2,2), mar=c(4,4,3,2))
plot(house.power$Date_Time, house.power$Global_active_power, type='l', xlab='', ylab='Global Active Power', cex.lab=0.8)
plot(house.power$Date_Time, house.power$Voltage, type='l', xlab='datetime', ylab='Voltage', cex.lab=0.8)
plot(house.power$Date_Time, house.power$Sub_metering_1, type = 'n', xlab='', ylab='Energy sub Metering', cex.lab=0.8)
points(house.power$Date_Time, house.power$Sub_metering_1, type='l')
points(house.power$Date_Time, house.power$Sub_metering_2, type='l', col='red')
points(house.power$Date_Time, house.power$Sub_metering_3, type='l', col='blue')
legend('topright', legend = c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'), col = c('black', 'red', 'blue'), bty='n', lty=1, cex=0.8, text.width = 86000)
plot(house.power$Date_Time, house.power$Global_reactive_power, xlab='datetime', ylab='Global_reactive_power', type='l', cex.lab=0.8)
dev.copy(png, file='plot4.png')
dev.off()
